export const pageContent = {
  name: 'pageContent',
  title: 'Page Content',
  fieldset: 'pageBody',
  type: 'array',
  description: 'These are the conent blocks that will populate the body of the page.',
  of: [
    {type: 'accordion'},
    {type: 'affiliateList'},
    {type: 'ctaBlock'},
    {type: 'formCta'},
    {type: 'heroBanner'},
    {type: 'iconFeatures'},
    {type: 'imageBlock'},
    {type: 'imageGallery'},
    {type: 'logoHeroBanner'},
    {type: 'peopleListing'},
    {type: 'projectCollection'},
    {type: 'quotes'},
    {type: 'recentPosts'},
    {type: 'richText'},
    {type: 'river'},
  ],
}
